# -*- coding: utf-8 -*-
"""Level-2-chat-bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17y8_0onU3tXrA82CYBrDTu-dLhJmPlJC
"""

patterns = {
    "access":   ["access", "lost", "account", "login", "register", "where"],
    "expiry":   ["limited", "timeframe", "expires", "expiriry", "expire",
                 "limit", "time"],
    "release":  ["when", "release", "month", "date", "day", "released"],
    "revisited":["live", "revisited", "revisit", "visit", "rewatch"],
    "greeting": ["hi", "hey", "help", "hello", "how are you"],
    
}

class IntentClassifier(object):
  def __init__(self, patterns):
    self.patterns = patterns
  
  def classify(self, text):
    for intent, pattern in self.patterns.items():
      for word in pattern:
        if word in f" {text.lower()} ":
          return intent
    return "notfound"

  def generete_answer(self, intent):
    if intent == 'greeting':
      return "Hello. please ask me a question"
    if intent == 'access':
      return "You can only bid with an account at our website. PLease make an account."
    if intent == 'expiry':
      return "Your account will not expire, unless you choose to delete it."
    if intent == 'release':
      return "We are hoping to release the full software by tuesday next week"
    if intent == 'revisited':
      return 'The website can be revisited but the auctions are live unless the buyer re-auctions it.'

app = IntentClassifier(patterns)

for x in range(5):
  lets_test = input()
  print(app.generete_answer(app.classify(lets_test)))

